# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Photon Design System
email: designsystem@thunderbird.net
description: > # this means to ignore newlines until "baseurl:"
  The Photon Design System houses guidelines, reusable UI components, templates,
  and other resources to help you create products for Thunderbird users.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://design.thunderbird.net" # the base hostname & protocol for your site
twitter_username: firefoxux
github_username:  firefoxux

# Build settings
markdown: kramdown

collections:
  visuals:
    order: 1
    output: true
  motion:
    order: 2
    output: true
  patterns:
    order: 3
    output: true
  components:
    order: 4
    output: true
  resources:
    order: 5
    output: true
